# Generated by Django 3.1.5 on 2021-01-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=50)),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10)),
                ('BDate', models.DateField()),
                ('City', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('PName', models.CharField(max_length=50)),
                ('product_size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SName', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('SID', 'SName')},
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('WID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cart_status', models.CharField(choices=[('D', 'deleted'), ('O', 'ordered'), ('C', 'in_cart')], default='NULL', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='catalog.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UnitCost', models.IntegerField()),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier')),
            ],
            options={
                'unique_together': {('PID', 'SID')},
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('WID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.warehouse')),
            ],
            options={
                'unique_together': {('PID', 'WID')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('O', 'ordered'), ('S', 'in shipping'), ('F', 'finished')], max_length=1)),
                ('order_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('transaction_price', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalog.cart')),
            ],
            options={
                'unique_together': {('cart', 'OrderID')},
            },
        ),
    ]
