# Generated by Django 3.1.5 on 2021-01-18 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210116_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('PName', models.CharField(max_length=50)),
                ('product_size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=50)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('WID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='CID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='SID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cart_status', models.CharField(default='NULL', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='catalog.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('SID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.supplier')),
            ],
            options={
                'unique_together': {('PID', 'SID')},
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=0)),
                ('PID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('WID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.warehouse')),
            ],
            options={
                'unique_together': {('PID', 'WID')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=1)),
                ('order_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('transaction_price', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalog.cart')),
            ],
            options={
                'unique_together': {('cart', 'OrderID')},
            },
        ),
    ]
