# Generated by Django 3.1.5 on 2021-01-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210118_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='UnitCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_status',
            field=models.CharField(choices=[('D', 'deleted'), ('O', 'ordered'), ('C', 'in_cart')], default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=10),
        ),
    ]
