# Generated by Django 3.1.5 on 2021-01-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210118_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='CID',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
