# Generated by Django 3.1.5 on 2021-01-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210118_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='NO',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CID',
            field=models.CharField(max_length=10),
        ),
    ]
