# Generated by Django 3.1.5 on 2021-01-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20210118_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='UnitCost',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('O', 'ordered'), ('S', 'in shipping'), ('F', 'finished')], max_length=1),
        ),
    ]
