# Generated by Django 3.1.5 on 2021-01-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210118_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='UnitCost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
